management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,threaddump,heapdump,circuitbreakers,circuitbreakerevents
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 20
        failureRateThreshold: 50
        slowCallDurationThreshold: 2s
        slowCallRateThreshold: 50
        minimumNumberOfCalls: 10
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
    instances:
      inventory:               # <- instance name
        baseConfig: default
  retry:
    instances:
      inventory:
        maxAttempts: 3
        waitDuration: 300ms
        retryExceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
  timelimiter:
    instances:
      inventory:
        timeoutDuration: 3s
        cancelRunningFuture: true
  bulkhead:
    instances:
      inventory:
        maxConcurrentCalls: 20
        maxWaitDuration: 0
  ratelimiter:
    instances:
      inventory:
        limitForPeriod: 50
        limitRefreshPeriod: 1s
        timeoutDuration: 0
